name: "fraud-model"
platform: "onnxruntime_onnx"
input [
  { name: "dense_input" 
    dims: [-1, 7]
    data_type: TYPE_FP32 
  }
]
output [
    {
      name: "dense_3"
      data_type: TYPE_FP32
      dims: [-1, 1]
    }
]
